### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [vlazzarini/MUSICV#1]
I suggest adding the topics `music`, `audio` in the About section.

**Comment by vlazzarini** [comment]
thanks, where is that done actually?

**Comment by Beliavsky** [comment]
Please see https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics .

**Comment by vlazzarini** [comment]
done
